### ISSUE TITLE
(Bug) - Custom Figma plugins links broken

### ISSUE THREAD

**Issue by MadMango** [newscorp-ghfb/newskit#165]
# Describe the bug

I can't see the plugin examples for Figma, I think the permissions on those files might not be allowing outsiders? :D 

# To Reproduce
1. Go to https://newskit.co.uk/getting-started/design/design-overview/#plugins
2. Click on [View Theme Swapper Figma plugin](https://www.figma.com/community/plugin/968555028114672265/NK---Theme-Swapper) OR [View Theme Exporter Figma plugin](https://www.figma.com/community/plugin/934126878505200119/NK---Theme-Exporter)

# Expected behavior
I should be able to see the examples

# Screenshots / Video / Test Environment
![image](https://user-images.githubusercontent.com/7106600/163426093-337aca56-afbe-4aae-8b18-048ff1952765.png)

# Desktop (please complete the following information):
 - OS: Windows 11
 - Browser: Edge
 - Version 100.0.1185.39

# Additional context
*Add any other context about the problem here.*

**Comment by jps** [comment]
Copy updated to indicate internal only
