### ISSUE TITLE
(Bug) - Menu component documentation - sandbox

### ISSUE THREAD

**Issue by peterculak** [newscorp-ghfb/newskit#413]
# Describe the bug
Sandbox for menu is broken.

# To Reproduce
1. Go to https://www.newskit.co.uk/components/menu/
2. Click on "Edit on CodeSandbox" button

# Actual behavior
Sandbox opens in new window and error appears "DependencyNotFoundError
Could not find dependency: '@emotion/react' relative to '/node_modules/newskit/esm/theme/emotion.js'"

# Expected behavior
I'm expecting to see a working menu component with no javascript errors in console

# Screenshots / Video / Test Environment
<img width="1728" alt="Screenshot 2022-10-13 at 10 00 34" src="https://user-images.githubusercontent.com/1822307/195552458-57b4a96b-4b78-4c2f-b381-c5d7a7f53df4.png">

# Desktop (please complete the following information):
 - OS: macOS Monterey 12.6
 - Browser Chrome
 - Version 106.0.5249.103 (Official Build) (arm64)

# Additional context
*Add any other context about the problem here.*

**Comment by jps** [comment]
@peterculak thanks, we will look at fixing this in PPDSC-2479
