### ISSUE TITLE
newskitLightTheme

### ISSUE THREAD

**Issue by nishant-k1** [newscorp-ghfb/NewsKit#640]
npm link shows newskitLightTheme as a prop value that we can pass into theme prop for NewsKitProvider component.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/26035708/219049826-a9c578de-a361-46bf-b001-bc9c7fa95884.png">
But when we search for more details for newskitLightTheme on the [Newskit website](https://newskit.co.uk/), the search provide no details or results relating to it.

**Comment by jps** [comment]
sorry for the slow reply on this @nishant-k1 The base themes are essentially the defaults for the system and are documented in the theme section of the site, this page in particular details on how to use a theme in [code](https://www.newskit.co.uk/theme/theming/using-a-theme/)
