### ISSUE TITLE
Update text cropping component scenarios - Storybook

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#719]
# Description
Updates to the text cropping component scenarios- Storybook

# Tasks/Steps

Using the [designs](https://www.figma.com/file/jc7O1Y4HNKs6KbJEpTCb4y/NewsKit---Storybook-Project---Text?node-id=2313%3A260996&t=JJTN93Q7xy0A32jc-0) update the storybook pages for the text cropping component.

The designs include what should be on each page, and the title, description, and link to the documentation page on the site for the component.

Note the name of the pages also should be updated to match what we have in the designs.

Remove the `limitSizeDecorator` globally that we have in storybook, this was added due to a limitation in appliTools which we no longer have, we would possibly expect additional changed in the snapshots as a result of this. 

## Notes (main differences to what we have currently live versus the designs)

Can we use long page option in this case?

# Acceptance/Testing Criteria

Given I am in Storybook

When I view the text cropping component pages

Then the pages will be updated as per the [designs](https://www.figma.com/file/jc7O1Y4HNKs6KbJEpTCb4y/NewsKit---Storybook-Project---Text?node-id=2313%3A260996&t=JJTN93Q7xy0A32jc-0)

And the pages will be within 1024x768 for Applitools snapshots.

# Business Benefit/Value

Consistent text cropping component examples for consumers, aligning to the NK branding.

**Comment by mutebg** [comment]
@GeriReid @nathanparris  [Link](http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/719-text-cropping-scenarios/storybook/?path=/story/welcome--welcome)

**Comment by GeriReid** [comment]
Hi @mutebg, would it be possible to change the colour of the type and background? Realised the colours we've specced don't work in the dark theme.

Font colour: inkBase
Background container: interactivePrimary010 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/39526800/227989509-1843cbb2-2b07-436a-9ed0-30e24c3ff058.png">

Also, is it possible to move the order in the left nav so it sits alphabetically (under Text block):
<img width="430" alt="image" src="https://user-images.githubusercontent.com/39526800/227990844-1460ce99-d011-4c80-a342-5ccfe809c3d8.png">

Cheers Stoyan

**Comment by mutebg** [comment]
@GeriReid updated the colors,
also added alphabetic sort order to all stories, you will notice that all stories are sorted correctly, I am not sure what was the previous way of sorting.

**Comment by GeriReid** [comment]
Thanks for the colour change @mutebg, this one's good to move.
