### ISSUE TITLE
Update Select component scenarios - Storybook

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#721]
# Description

Select component scenarios- Storybook

# Tasks/Steps

Using the [designs](https://www.figma.com/file/jcPIIM3F3jloyKWzaHy3c1/NewsKit---Storybook-Project---Actions-and-Inputs?node-id=1909%3A394221&t=ehcT6PAkGXTjGyMP-1) create the storybook pages for the Progress indicator component.

The designs include what should be on each page, and the title, description, and link to the documentation page on the site for the component.

Note the name of the pages also should be updated to match what we have in the designs.

Notes (main differences to what we have currently live versus the designs)

Not currently in Storybook, new story

# Acceptance/Testing Criteria

Given I am in Storybook

When I view the Progress indicator component pages

Then the pages will be as per the [designs](https://www.figma.com/file/phmWaRMlkssTtbv88pPVDl/NewsKit---Storybook-Project---Feedback-and-Status?node-id=1875%3A487822&t=6bbeYQ9UB1C6hVik-0)

And the pages will be within 1024x768 for Applitools snapshots.

# Business Benefit/Value

Consistent Progress indicator component examples for consumers, aligning to the NK branding.

**Comment by JohnTParsons** [comment]
@GeriReid @nathanparris Please design review https://github.com/newscorp-ghfb/NewsKit/pull/807

I've added a new cross on circle icon (as per Figma) but could not get it to display as white on black, but perhaps might do?

In Overrides, I've added more stories than asked for, as was experimenting with different combinations of padding and margin props to see what the effect was.

**Comment by JohnTParsons** [comment]
@GeriReid Above 3 changes pushed

**Comment by nathanparris** [comment]
@JohnTParsons  Looking good. Just a few small points from me

**z-index test**
- Can you add style presets to the div
`editorialParagraph010`, `inkBase`
Background: `interfaceNeutral020`


**Styling overrides**
- selectPanelCustom2
Can you add `backgroundColor: '{{colors.interface010}}',   boxShadow: '{{shadows.shadow050}}',`
- selectOptionCustom2
  Add `hover: { backgroundColor: '{{colors.interactiveInput010}}',`

**Overrides**
-  Custom icon is too subtle a change making bigger, can you try `IconFilledArrowDropDown`

**Comment by JohnTParsons** [comment]
@nathanparris Those changes pushed

**Comment by nathanparris** [comment]
@JohnTParsons Sorry, the selectOptionCustom2 is failing contrast on dark theme.
Can you update this to `hover: { backgroundColor: '{{colors.interactiveInput030}}',`

This colour is the same for light theme, but is a darker shade on the dark theme.

**Comment by JohnTParsons** [comment]
@nathanparris Change pushed

**Comment by JohnTParsons** [comment]
PR link: https://github.com/newscorp-ghfb/NewsKit/pull/807
