### ISSUE TITLE
Update Slider component scenarios - Storybook

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#722]
Updates to the Slider component scenarios- Storybook

# Tasks/Steps

- Using the [designs](https://www.figma.com/file/jcPIIM3F3jloyKWzaHy3c1/NewsKit---Storybook-Project---Actions-and-Inputs?node-id=1907%3A435898&t=QyxWz6VYq3a7qbss-0) update the storybook pages for the Slider component.
- The designs include what should be on each page, and the title, description, and link to the documentation page on the site for the component.
- Note the name of the pages also should be updated to match what we have in the designs.

## Notes (main differences to what we have currently live versus the designs)
- Added a ‘States’ page.
- Added a vertical sliders to all pages, and omitted the Vertical Slider examples page.
- Added a ‘Variations’ page that includes the 2 thumbs, and slider with labels examples.
- Added examples of the slider track size and the thumb border radius overridden.
- Slider with custom labels examples reduced and moved to the ‘Overrides’ page.
- Slider with custom style presets page omitted.
- Slider with custom renderers page omitted.
- Reduced the outline override example to one on the ‘Overrides’ page.
- Added Icon component override to the ‘Overrides’ page.
- Updated the label copy on the ‘Overrides’ page.
- Logical props example moved to the ‘Overrides’ page.

# Acceptance/Testing Criteria

Given I am in Storybook

When I view the Slider component pages

Then the pages will be updated as per the [designs](https://www.figma.com/file/jcPIIM3F3jloyKWzaHy3c1/NewsKit---Storybook-Project---Actions-and-Inputs?node-id=1907%3A435898&t=QyxWz6VYq3a7qbss-0)

# Business Benefit/Value

Consistent Slider component examples for consumers, aligning to the NK branding.

**Comment by jannuk59** [comment]
@nathanparris http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/722-update-slider-component-storybook-scenarios/storybook/?path=/docs/components-slider--story-slider-default Slider component scenario enhancement is ready for design review

**Comment by nathanparris** [comment]
@jannuk59 Thanks for sharing. Please see some feedback below:

### General
- Add description and documentation link to below the page title. 
Sliders allow users to choose a single value or range between min and max values by sliding a thumb.

### States
- Remove test from "Horizontal test" title
- Horizontal focus - remove thumb label

### Horizontal slider with labels
- Label positioned above thumb - can you add some space between the title and label so they don't overlap
<img width="295" alt="image" src="https://user-images.githubusercontent.com/108727455/233936961-d9cc8956-234c-40ff-bf3f-2244df97bc11.png">

- Min and max labels-  Update title to with inline "Both min and max inline labels"
- Label position before/after - update to "Labels positioned before/after"

### Vertical slider with labels
- Is there a way that the label can align vertically with the thumb?
<img width="248" alt="image" src="https://user-images.githubusercontent.com/108727455/233938693-c929d0b1-0ce6-4d79-9ad2-c15325e3e50f.png">

### Styling overrides
- Change label colour to inkBrand010
- Changed feedback background colour to `interactiveSecondary030`

### Overrides
- Icons too small not changing colour in dark theme. Can you update to       
`size: 'iconSize020',  stylePreset: 'inkBase',`
- Change this title to "Custom outline"
<img width="314" alt="image" src="https://user-images.githubusercontent.com/108727455/233942513-358abf57-20a9-4666-9dba-33c78a772e67.png">

- Track size - Can't see any override being applied here. Change to `sizing010`

**Comment by jannuk59** [comment]
Hi @nathanparris The feedback has been updated. Please have a re-review on it. http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/722-update-slider-component-storybook-scenarios/storybook/?path=/docs/components-slider--story-slider-default

**Comment by jannuk59** [comment]
@GeriReid couple of feedback mentioned above has been fixed.

**Comment by GeriReid** [comment]
@jannuk59 thanks for the edits, good to go from me. @nathanparris pls have a final look. thanks

**Comment by nathanparris** [comment]
All good for me, except the bug with thumb label position on the vertical slider.
Maybe this could be added as a new bug ticket if you can't solve it now.

**Comment by jannuk59** [comment]
Will try to fix it @nathanparris. Seems we can't done with overrides.

**Comment by jannuk59** [comment]
Hi @nathanparris I have fixed the issue. But not sure whether its good practice to go with. I will check with other engineers and let you know here. 

![Image](https://user-images.githubusercontent.com/19908125/234774464-6b3fba47-f63c-4193-9fa6-18021af827a0.png)

**Comment by jannuk59** [comment]
@nathanparris @GeriReid Seems we need a separate ticket to fix thumbLabel vertically centre to the thumb in the slider to find proper solution with the team. 

Thanks. 

cc: @mutebg
