### ISSUE TITLE
Update Standfirst component scenarios - Storybook

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#723]
# Description

Updates to the Standfirst component scenarios- Storybook

# Tasks/Steps

- Using the [designs](https://www.figma.com/file/jc7O1Y4HNKs6KbJEpTCb4y/NewsKit---Storybook-Project---Text?node-id=2260%3A254848&t=UyLK00cgrfybeuKN-0) update the storybook pages for the Standfirst component.
- The designs include what should be on each page, and the title, description, and link to the documentation page on the site for the component.
- Note the name of the pages also should be updated to match what we have in the designs.

# Acceptance/Testing Criteria

Given I am in Storybook

When I view the Standfirst component pages

Then the pages will be updated as per the [designs](https://www.figma.com/file/jc7O1Y4HNKs6KbJEpTCb4y/NewsKit---Storybook-Project---Text?node-id=2260%3A254848&t=UyLK00cgrfybeuKN-0)

And the pages will be within 1024x768 for Applitools snapshots.

# Business Benefit/Value

Consistent Standfirst component examples for consumers, aligning to the NK branding.

**Comment by jannuk59** [comment]
@GeriReid @nathanparris http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/723-standfirst-storybook/storybook/?path=/docs/components-standfirst--story-default is ready for design review.

**Comment by nathanparris** [comment]
@jannuk59 Looks good for me too.

**Comment by jannuk59** [comment]
Thanks @GeriReid and @nathanparris. Moving to peer review in a while.

**Comment by jannuk59** [comment]
@GeriReid and @nathanparris Please have a look at the PR comments https://github.com/newscorp-ghfb/NewsKit/pull/881 on using typographyPreset for the standfirst component and let me know your suggestions.
