### ISSUE TITLE
Update Title bar component scenarios - Storybook

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#725]
# Description 

Updates to the Title bar component scenarios- Storybook

# Tasks/Steps

- Using the [designs](https://www.figma.com/file/p6y4PiszwldPZfb7bhde4F/NewsKit---Storybook-Project---Navigation?node-id=2290%3A426382&t=A3f8iLadb6LQUqHi-1) update the storybook pages for the Title bar component.
- The designs include what should be on each page, and the title, description, and link to the documentation page on the site for the component.
- Note the name of the pages also should be updated to match what we have in the designs.

### Notes (main differences to what we have currently live versus the designs)

- Remove title-bar, added variations to other stories
- Default - new story
- Variations - new story
- Overrides - new story

# Acceptance/Testing Criteria

Given I am in Storybook
When I view the Title bar component pages
Then the pages will be updated as per the [designs](https://www.figma.com/file/Wfh75ezgYOD1aGNoohFA8h/NewsKit---Storybook-Project---Media?node-id=2081%3A108189&t=AobGjgZIFcrbO9cB-0)
And the pages will be within 1024x768 for Applitools snapshots.

# Business Benefit/Value

Consistent Title bar component examples for consumers, aligning to the NK branding.

**Comment by jannuk59** [comment]
@GeriReid and @nathanparris Please have review on it http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/725-titlebar-storybook/storybook/?path=/docs/components-title-bar--story-title-bar-default

**Comment by GeriReid** [comment]
thanks @jannuk59. 

- On the examples without a heading could you please remove the extra padding above the title, so it sits centrally:
<img width="592" alt="image" src="https://github.com/newscorp-ghfb/NewsKit/assets/39526800/210be2dc-4464-4498-b90d-4f3cdb3d1979">

- Logical Props - lowercase p in the heading please to read Logical **p**rops

Rest looks good, thanks :)

**Comment by jannuk59** [comment]
@nathanparris removed extra gap at the top of the title bar when we dont have heading. Please have a review at it http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/725-titlebar-storybook/storybook/?path=/docs/components-title-bar--story-title-bar

**Comment by nathanparris** [comment]
@jannuk59 Looks good to me

**Comment by jannuk59** [comment]
Thanks @nathanparris. Moving to peer review
