### ISSUE TITLE
Update Video player  component scenarios - Storybook

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#730]
# Description

Updates to the Video player component scenarios- Storybook

## Tasks/Steps

- Using the [designs](https://www.figma.com/file/Wfh75ezgYOD1aGNoohFA8h/NewsKit---Storybook-Project---Media?node-id=2081%3A108189&t=WQBTvhyeIucOyXmc-1) update the storybook pages for the Video Player component.
- The designs include what should be on each page, and the title, description, and link to the documentation page on the site for the component.
- Note the name of the pages also should be updated to match what we have in the designs.

### Notes (main differences to what we have currently live versus the designs)

- Default: removed variations - moved to own story
- Placements and placements visual test - use what currently stands (screenshots below)
- Variations: new story
- Overrides: change colours and styles

## Acceptance/Testing Criteria

- Given I am in Storybook
- When I view the Video Player component pages
- Then the pages will be updated as per the [designs](https://www.figma.com/file/phmWaRMlkssTtbv88pPVDl/NewsKit---Storybook-Project---Feedback-and-Status?node-id=2099%3A250935&t=lazzs0J7ciYi4d5g-0)
- And the pages will be within `1024x768` for Applitools snapshots.

## Business Benefit/Value

Consistent Video Player component examples for consumers, aligning to the NK branding.

**Comment by JohnTParsons** [comment]
PR is https://github.com/newscorp-ghfb/NewsKit/pull/830

@nathanparris ready for design review

**Comment by nathanparris** [comment]
@JohnTParsons Some feedback below:
- Can you add a link to Brightcover player in the introduction text https://player.support.brightcove.com/getting-started/index.html (as shown in the design layout)
- Styling overrides not matching design - I updated the play button example to a solid fill (was an icon change before)
- There is an issue with the component defaults, where the title uses color the `white` token so this doesn't theme correctly in dark. Can this be updated to `inkInverse`.

**Comment by JohnTParsons** [comment]
Moving from Design Review to Peer Review
