### ISSUE TITLE
Migrate NewsKit Demo into the main NewsKit Repo

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#731]
# Description

Currently, the NewsKit Demo is living in a separate repo outside of the organisation, this means that it is often overlooked when we want to make changes. We would like to migrate it to live within the NewsKit site so that it is available under the route https://newskit.co.uk/demo

The Demo site is used as a resource when presenting onboarding to new users for NewsKit

# Links

https://newskit-demo.vercel.app/
https://github.com/lhaggar/newskit-demo 

# Tasks/Steps

- Migrate pages into the NewsKit Site
- Do any migrations required for NewsKit 7
- Ask Lewis to archive the old repo 
- Use `GridLayout` instead of Stack for the layout
- Use Themes from Publisher in the demo
    - Remove Virgin? Add in Dow Jones
- Make notes for any additional improvements

> Please make sure we are not adding fonts into the repo that we don’t have rights for! 

# Acceptance/Testing Criteria

As a user of the NewsKit site, I can access the demo on the same domain as the documentation.

**Comment by mutebg** [comment]
DJ theme has been updated @GeriReid & @nathanparris can you review it again please? http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/731-add-demo/demo/

**Comment by nathanparris** [comment]
@mutebg From a theming perspective, the fonts are correct for Dow Jones and Wall Street Journal, falling back to Times New Roman so assume these are not loading in.

**Comment by mutebg** [comment]
Fixed the fonts

**Comment by nathanparris** [comment]
Thanks @mutebg Themes look good now.
