### ISSUE TITLE
Inline Drawer pushes the content

### ISSUE THREAD

**Issue by mutebg** [newscorp-ghfb/NewsKit#732]
# Describe the bug
*A clear and concise description of what the bug is.*

# To Reproduce
1. Go to Inline Drawer Storybook ( https://storybook.newskit.co.uk/?path=/story/components-drawer--story-inline )
2. Click on "Right" button
3. During the opening transition, the content outside the drawer its been pushed ( check the attached video )

# Expected behavior
*A clear and concise description of what you expected to happen.*

# Screenshots / Video / Test Environment

https://user-images.githubusercontent.com/3543332/226903649-4af387c4-4254-41f2-997e-445a855f0a25.mov

# Desktop (please complete the following information):
 - OS: iOS
 - Browser: Chrome, Safari, Firefox
 - Version: latests

# Additional context
*Add any other context about the problem here.*

**Comment by mstuartf** [comment]
This only happens from the second render onwards. It looks like the drawer starts in a hidden state on the left but then ends in a hidden state on the right.

**Comment by mstuartf** [comment]
![Image](https://user-images.githubusercontent.com/26839368/232467993-67763f6b-36d1-4a6e-bbd5-91abec690c04.png)
![Image](https://user-images.githubusercontent.com/26839368/232467995-19cbb11b-22bd-4450-bbae-b6953a9aed67.png)
![Image](https://user-images.githubusercontent.com/26839368/232467996-d86717df-87fb-4f56-ba9c-633ac61e403b.png)

**Comment by mstuartf** [comment]
It looks like this is related to `MoveFocusInside`. Swapping that for a `div` prevents the issue.
