### ISSUE TITLE
Update font-smoothing - Storybook

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#740]
# Description

We noticed when reviewing the latest from the solutions team that fonts are rendering lighter than on our Storybook.

Delivery instructions - https://newskit-render.ceng-dev.newsuk.tech/account/edit/delivery-instructions

# Tasks/Steps

There is a CSS property `-webkit-font-smoothing: antialiased;` causing this.

Not sure what the default should be?

Should this also be an update to the NK Light theme in code?

Probably should be added to Storybook, as it is there on the docs site (left is storybook, right is from solutions):

We should add it globally to storybook

Review with design when ready.

**Comment by GeriReid** [comment]
Thanks @mutebg, looks good to Nathan and me - you're good to move this one.
