### ISSUE TITLE
Remove AWS/EKS env vars from Circle

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#744]
# Description

**NB K8S/EKS and DNS resources should be destroyed first (see related tickets PPDSC-2863 and PPDSC-2864).**

Cleanup Circle only when the above AWS cleanup is complete in case the existing env vars are needed by Terraform as part of the resource destruction process. ie

1. Remove secrets-related AWS_* env vars from contexts (EXCEPT for AWS_DEFAULT_REGION and S3_AWS_ASSUME_ROLE_ARN)
2. Remove ECR_* env vars from contexts.
3. Remove also any variables that are not needed anymore from Newskit project env variables (is not a context)

# Acceptance Criteria

Pipeline still works (should do as Xin has already removed k8s and eks steps)

Circle secrets Confluence page updated: https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/4267081936/DS+Circle+CI+-+Secrets+Overview

**Comment by JohnTParsons** [comment]
Blocked until infra eng have finished destroying related AWS resources

**Comment by JohnTParsons** [comment]
Have done (1) and (3) but cannot do (2) as https://app.circleci.com/settings/project/github/newscorp-ghfb/newskit/environment-variables?return-to=%2F now displays, "Error! Project not found".

**Comment by JohnTParsons** [comment]
Have deleted AWS_* secrets from ncu-newskit-site-dev, ncu-newskit-site-stage and ncu-newskit-site-prod
BUT have not deleted secrets from ncu-product-platforms-context as Confluence says that context is being used by Publisher (so extra checks will be required to see if that is using AWS secrets).
