### ISSUE TITLE
Fix DateTime structure

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#745]
# Description

Following up on the [spike](https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/4325900327/time+Investigation) in the DateTime structure we want to improve our component to be HTML standards compliant and bring A11Y and SEO improvements.

Current HTML structure:

```
<time>
    <span>Updated: </span>
    <span>January 1 2017, 6:32am</span>
    <span>The Times</span>
</time>
```

We would like it to be:

```
<p>
    <span>Updated:</span>
    <time datetime="2017-01-01T11:00:00.000Z">January 1 2017, 6:32am</time>,
    <span>The Times</span>
</p>
```

- prefix and suffix outside the time html tag 
- a dateTime attribute should be set using the date property currently passed by consumers. 

We would expect what they pass to be in a machine-readable format, so should fit the datetime attribute requirements and at the same time be translated into something more human-readable for the visual text. We can use same format function from data-fns to to convert to correct machine format `dateTime={format(new Date(date), 'ISO2012')}`

We may want to allow consumers to override the text we create with a new Date, so rather than `January 1 2017, 6:32am` the user may want to write `yesterday` . I would propose to achieve this by passing a string as a child of DateTime prop.

# Tasks/Steps

- Update docs with a new option to pass children
- Add storybook scenarios with children and date attributes.

# Acceptance/Testing Criteria

This should be a non-breaking change for the user, existing scenarios should be visually the same

# Supporting Information

(Process/sequence flows, wireframes, third-party documentation, tech feasibility, architecture overview/documentation, high-level design, data specs etc...)

# Dependencies

(Any known business dependencies or reasons to engage with another team and input into their roadmap/timings)

**Comment by mutebg** [comment]
@GeriReid @nathanparris the ticket is ready for design review.
From your point of view only few things changed:
- 2 new stories have been added to variations: `Custom date format` and `With children` ->  http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/745-date-time-structure/storybook/?path=/docs/components-date-time--story-date-time-default
- `children` prop has been added to API table in docs -> http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/745-date-time-structure/components/date-time/

**Comment by GeriReid** [comment]
@mutebg looks good, thanks for updating props table.
