### ISSUE TITLE
(Bug) - svg images on docs sites are not displaying correctly in Chrome

### ISSUE THREAD

**Issue by GeriReid** [newscorp-ghfb/NewsKit#752]
# Describe the bug
Some svg images on the docs site are not displaying correctly in chromium browsers. Affects both dark and light themes. Fine in Safari and Firefox.

# To Reproduce
1. Go to the [About page](https://www.newskit.co.uk/about/overview/)
2. Scroll down to 'Why use NewsKit
3. Images are missing some vector shapes:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/39526800/227219164-6e37dc47-4ac4-4caf-a9d2-37e69c6b3fe7.png">

# Expected behaviour
Compare to images in Safari or Firefox
<img width="936" alt="image" src="https://user-images.githubusercontent.com/39526800/227219623-30f99dbd-be52-45bd-a8d3-969b5ce3de3b.png">

Affects most screens with images. On some screens the images are not displaying - scroll to Options
https://www.newskit.co.uk/components/accordion/#options

# Desktop:
 - OSX
 - Browser Chrome
 - Version 111.0.5563.64 (Official Build) (arm64)

Displaying correctly in Chrome on iOS on iPhone 12

**Comment by mutebg** [comment]
Link to Opened Issue in in Chromium -> https://bugs.chromium.org/p/chromium/issues/detail?id=1429510

**Comment by mutebg** [comment]
@GeriReid @nathanparris link for review -> http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/752-svg-issue/ 
I removed all filters from SVGs so some of them might lack some of the details like shadows

**Comment by nathanparris** [comment]
@mutebg @GeriReid Looks OK to me. If we think anything is really lacking contrast, then we could just update those images with a border (or another solution).

**Comment by GeriReid** [comment]
Agree - some images look a bit flat but better than what is live. Suggest we go with it. If you can keep a copy of the originals we can replace if Chrome updates.
