### ISSUE TITLE
Implement slack notifications for new issues and discussion

### ISSUE THREAD

**Issue by Vanals** [newscorp-ghfb/NewsKit#762]
# Description
Now that we are moving more and more towards GitHub and our consumers will be posting in discussions and issues we want to be aware when new requests are made, so we can promptly reply and help.

# Tasks/Steps
Do some research and find the best approach, and/or try the solution suggested.
Implement slack notifications so when new discussions or issues are created we can be notified.
Where? channel ad hoc I think would be appropriated. otherwise may be too spammy, we also created issues?

# Acceptance Criteria
Notifications should be sent to the dedicated channel when new issue or discussion is created

# Supporting Information
*Process/sequence flows, wireframes, third party documentation, tech feasibility, architecture overview/documentation, high level design, data specs etc...*

TRY THIS METHOD FROM CHATGPT:

```
Sure, you can use Slack apps to receive notifications when new discussions or issues are created in your GitHub repository. Here's how to set it up:

Create a new Slack app by going to https://api.slack.com/apps and clicking on the "Create New App" button.

Give your app a name and select the workspace where you want to use it.

In the "Add features and functionality" section, click on "Incoming Webhooks" and turn it on.

Click on "Add New Webhook to Workspace" and select the channel where you want to receive the notifications.

Copy the Webhook URL that is generated.

Go to your GitHub repository and click on the "Settings" tab.

Click on "Webhooks" in the left-hand menu.

Click on the "Add webhook" button.

Paste the Webhook URL you copied from Slack into the "Payload URL" field.

In the "Content type" field, select "application/json".

In the "Which events would you like to trigger this webhook?" section, select "Let me select individual events" and then select "Issues" and "Discussion" from the list.

Click on the "Add webhook" button to save the webhook.

Now, whenever a new discussion or issue is created in your GitHub repository, you should receive a notification in the Slack channel you selected. You can customize the notification message by going to the "Incoming Webhooks" section of your Slack app and editing the settings for the webhook.
```

**Comment by jps** [comment]
@Vanals  It might be worth looking at #newskit-pull-requests as the GitHub integration we have on there looks to already be achieving this?

**Comment by LukeFinch** [comment]
We will keep reviewing the process in our team retrospectives – For now, we don't think a slack integration is the best use of time.
