### ISSUE TITLE
NewsKitReleaseBot migration & publicity tasks

### ISSUE THREAD

**Issue by JohnTParsons** [newscorp-ghfb/NewsKit#779]
# Description
Small changes that need doing before the next release.

# Tasks/Steps

1. Remove dependency on JIRA (and its Ready To Deploy column)
2. Remove the bot from #newskit-all-team - done at the channel level in slack
3. Remove the bot from #newskit-broadcast-support - done at the channel level in slack
4. Move tickets to done

# Acceptance Criteria
*All acceptance criteria must be met before task can be marked as 'done'*

# Supporting Information
- Repository: https://github.com/newscorp-ghfb/newskit-release-bot

# Dependencies
*Any known business dependencies or reasons to engage with another team and input into their roadmap/timings*

**Comment by mutebg** [comment]
1 and 4 are implemented, however I don't have permission to remove the bot from channels @jps @mstuartf  can you someone of you do that?

**Comment by jps** [comment]
@mutebg 
2. Looks like it isn't posting to #newskit-all-team
3. I've kicked the bot from the channel, will have to see if it comes back on the next release.
