### ISSUE TITLE
Docs site page for Card Composable

### ISSUE THREAD

**Issue by JohnTParsons** [newscorp-ghfb/NewsKit#822]
# Description
Implement the docs site page based on [Design's](https://www.figma.com/file/zsrAPjQudr5zB3uuXSEc6f/02---NK-Web---Components---Card-Composable?node-id=1-6&t=gab6jgayPTIj66v5-0 )
# Business Benefit/Value
Standard part of new component release

# Acceptance Criteria
Should match designs

# Design
[Illustrations files](https://drive.google.com/drive/folders/1txJNY7nB62hv3Y00Ges4jUcviS__u4SL?usp=sharing)

# Supporting Information
*Process/sequence flows, wireframes, third party documentation, tech feasibility, architecture overview/documentation, high level design, data specs etc...*

# Dependencies
*Any known business dependencies or reasons to engage with another team and input into their roadmap/timings*

**Comment by jannuk59** [comment]
http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/822-card-composable-doc-site/components/card-composable/ is ready for design review.

**Comment by GeriReid** [comment]
Thanks @jannuk59, looking good - a few edits please:

**Options: Card as a Link**

* Please format the word expand:

![Image](https://user-images.githubusercontent.com/39526800/236473657-f2307a35-5047-41c4-9a88-22af58975cc1.png)

as code, like this: 
![Image](https://user-images.githubusercontent.com/39526800/236477436-e56e06ab-0dc1-40b0-8267-60060bfdfbce.png)



- **Usage: Don’t use varying heights in a group of cards**
Add a link to the MDN reference: [Card - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Card)

- **Accessibility considerations**
Please remove all full stops, for consistency

Please indent these three bullets - see the design:
![Image](https://user-images.githubusercontent.com/39526800/236475816-9d3efe82-d2c5-4db3-b387-86955d98e617.png)

- Last bullet - please format the word _expand_ as code

- Please change the copy
"Don't wrap the whole card in a Link, use //expand// prop to make it look like it."
to
"Don't wrap the whole card in a Link, use the //expand// prop to make it interactive"

- **WAI-ARIA**
Please change this text
![Image](https://user-images.githubusercontent.com/39526800/236476533-67bc9340-474f-49d8-9f73-6e61de256551.png)
New text: Image alt text, if the image is not decorative. Alt text needs to be different from the card title.


- **SEO considerations**
Remove all full stops


Thanks Janani, have a great weekend!

**Comment by nathanparris** [comment]
@jannuk59 Looks good. Just a few additional comments:

- Anatomy section - add link to "Link Standalone" https://newskit.co.uk/components/link/
- Related components section - Only include Grid Layout
- Below the CardComposable API table there should be an inline message
![image](https://user-images.githubusercontent.com/108727455/237030190-4333e983-1035-491e-bb4d-a88521b0bd3c.png)

**Comment by jannuk59** [comment]
@GeriReid @nathanparris is ready for re-review

**Comment by GeriReid** [comment]
thanks @jannuk59, could you please add the word "prop" back in after expand in these two places? So it reads `expand` prop:

![image](https://github.com/newscorp-ghfb/NewsKit/assets/39526800/0821bcd5-ec6b-4abb-aadf-3132454169b6)
![image](https://github.com/newscorp-ghfb/NewsKit/assets/39526800/5b734905-fdbd-49ae-b567-3e2d16cf88f4)

Nathan also suggested in the related components section to only include Grid Layout, instead of the 4 current components.

thanks!

**Comment by jannuk59** [comment]
@GeriReid Updated the changes please have a look at it.

**Comment by GeriReid** [comment]
Looks good, thanks for the edits @jannuk59 - happy to approve.
