### ISSUE TITLE
Select component causes page jump when below the fold

### ISSUE THREAD

**Issue by tbradbury** [newscorp-ghfb/NewsKit#825]
# Describe the bug
*A clear and concise description of what the bug is.*

Select component on Account Address page - [https://newskit-render.ceng-dev.newsuk.tech/account/edit/address](https://newskit-render.ceng-dev.newsuk.tech/account/edit/address) results in page jump when opened for first time.

# To Reproduce
1. Go to - [https://newskit-render.ceng-dev.newsuk.tech/account/edit/address](https://newskit-render.ceng-dev.newsuk.tech/account/edit/address)
2. Click on country select
3. See page jump

# Expected behavior
*A clear and concise description of what you expected to happen.*
No page jump. I believe the solution is to add `position: relative;` to the div class name `nk-layer` around the `select-panel` div.

# Screenshots / Video / Test Environment
*If applicable, add screenshots to help explain your problem.*

Without:
![Screenshot 2023-04-12 at 10 13 41 am](https://user-images.githubusercontent.com/11298045/231428265-bdbfdbde-0c26-4584-a517-9882d098672b.png)

results in jump:
![Screenshot 2023-04-12 at 10 13 54 am](https://user-images.githubusercontent.com/11298045/231428353-c7533848-e24a-48ed-91b5-7e1413e082fd.png)

adding `position: relative;`
![Screenshot 2023-04-12 at 10 14 23 am](https://user-images.githubusercontent.com/11298045/231428438-9020f8b5-0fbe-4629-924c-ec9c6f027492.png)

# Desktop (please complete the following information):

# Smartphone (please complete the following information):

# Additional context
*Add any other context about the problem here.*

**Comment by tbradbury** [comment]
Seems we can sort this without changing Newskit code.

Select component has a property zIndex on the panel. Its default is layer if you change it to something else no-layer the dropdown options are put in a fragment under the select input and not at the bottom of the page. 

We can then add the position:relative around that one select component and the jumping stops without affecting anything else.

Maybe worth updating docs to explain how Select uses Layer. I can’t see anything about it in the override api section.

**Comment by jps** [comment]
Thanks @tbradbury, some good feedback here. We will look to improve the documentation around the layer manager and remove the legacy props which are causing confusion in https://github.com/newscorp-ghfb/NewsKit/issues/831
