### ISSUE TITLE
Provide fallback fonts in the newskit-themes-publisher

### ISSUE THREAD

**Issue by dj-kmuldoon** [newscorp-ghfb/NewsKit#826]
It is traditional to offer fallback fonts for Serif/SanSerif typography. Suggest making a look-up-table for each style and append a default set of fallbacks. Creating an easy process for engineers to add custom fallbacks would be great.

**Comment by LukeFinch** [comment]
This is definitely an opportunity to be a  great enhancement to the publisher.

I would be keen to see a PR in the publisher repository for how you think we could achieve this with the Tokens Studio pipeline.
