### ISSUE TITLE
Brands + SubBrands

### ISSUE THREAD

**Issue by dj-kmuldoon** [newscorp-ghfb/NewsKit#827]
Can the following snippet be updated to clearly show how WSJ may expect tokens output from Figma to be consumed in React environments by engineers where multiple sub-brands are represented in the same Figma file?

https://github.com/newscorp-ghfb/NewsKit/blob/4e9e91e801a869c2d3e06ace909c39fad7e2d7b0/site/theme/doc-theme.ts

**EXAMPLE:** 

WSJ has subbrands Live Journal and Opinion (WSJ-LJ/WSJ-OPN). Assuming an NK aligned folder structure in Figma which included these two subbrands, how might that be rendered into NewsKit format v5 via NK Themes Exporter? How does the engineer transform that into dark/light modes. 

Thanks!

**Comment by jps** [comment]
hey @dj-kmuldoon 

We currently have an open PR that will hopefully address what you are after

see `site/theme/__tests__/doc-theme.test.ts` in https://github.com/newscorp-ghfb/NewsKit/pull/718/files#diff-5a57106ac8131dc21f047b2fd62748fefc904c3204d1234aba4821747ba8d746

**Comment by jps** [comment]
@dj-kmuldoon 
closing as above PR has now been merged please see https://github.com/newscorp-ghfb/NewsKit/blob/main/site/theme/doc-theme.ts
