### ISSUE TITLE
Composed Section – Grid layout storybook examples using composable card

### ISSUE THREAD

**Issue by n-dorman** [newscorp-ghfb/NewsKit#852]
# Description
The grid layout storybook examples should be updated to use the composable card. Specific examples that cover use cases for The Sun and The Times will encourage them to use NewsKit for their solutions.

# Task

Create 'composed' section in Storybook

- add composed layouts for The Sun and the Times according to designs under "Slices" story
- migrate 'form complete' under 'Forms" story.

# Acceptance Criteria

New layouts built in storybook
Reviewed with design

- [Designs](https://www.figma.com/file/ieE2p1e8ZEZtfqPwOAvSwf/NewsKit---Storybook-Project---Layout?node-id=2117-28298&t=8n0QD6gk5d6dmum4-11)
- [Handoff for The Times cards](https://www.figma.com/file/ieE2p1e8ZEZtfqPwOAvSwf/NewsKit---Storybook-Project---Layout?type=design&node-id=3013-615773&t=SMyLi18n4NRC4tjn-11)

Sun card examples have already been built by Xin
- [Sun card examples Storybook](http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/ppdsc-0100-add-sun-composable-card-example/storybook/?path=/docs/components-cardcomposable--the-sun-story)

**Comment by mutebg** [comment]
@GeriReid @nathanparris ready for review http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/852-composed-section/storybook/?path=/story/composed-slices--the-sun-story

**Comment by GeriReid** [comment]
Thanks @mutebg, these are looking great. I'll leave Nathan to dig into the detail as he worked on the design but a few minor spots from me:
- on The Sun example could you change the text of the first article from the Lorem Ipsum to be consistent with the other cards, text: 

**KICKER Short title of the card describing the main content**
Short paragraph description of the article, outlining main story and focus.

- on The Sun example the focus ring is being cut off - could it appear like the Times examples?
<img width="803" alt="image" src="https://github.com/newscorp-ghfb/NewsKit/assets/39526800/92eee9e1-fa84-4cee-8586-b356f991f804">

- Heading levels. The Title bar on the Times example is an H3 and other other headings are H1s. All Sun headings are H1s. Should we be showing heading levels in this example as best practice or is it better to show component examples without overrides?

**Comment by nathanparris** [comment]
@mutebg Looking really good. 
Just a few points for the Times slice.

- Lead card
  - Divider - add paddingBlockEnd: space020
  
- SecondLevelCard
  - RowGap is showing at the bottom of all cards, and top and bottom on LG
  
 - All headlines: Can you add a stylePreset to these
   - Base: inkContrast, text decoration: none
   - Hover: interactiveLink020, text decoration: none
   - 'focus-visible': defaultFocusVisible,

**Comment by mutebg** [comment]
@GeriReid what' do you think is a good example for headings? IMO:
The Sun -> all cards H3, usually the whole section needs H2 ( we don't have such in the design ) and H1 for the whole page

The Times -> all cards H3, TitleBar: H2, and the page has H1

**Comment by GeriReid** [comment]
@mutebg thanks Stoyan - your suggestion sounds logical, let's go with that.

**Comment by mutebg** [comment]
all feedback has been addressed.
the only difference I made is that hovering on the whole card will change the headline ( there is no easy way to hover only on title )

**Comment by mutebg** [comment]
ready for review again. thanks @nathanparris

**Comment by nathanparris** [comment]
@mutebg Looks good. Thanks
