### ISSUE TITLE
Investigate accessibility requirements for native mobile platforms

### ISSUE THREAD

**Issue by n-dorman** [newscorp-ghfb/NewsKit#883]
As NewsKit moves more into native mobile support, ensure we can offer the same degree of support that we provide for the web. Accessibility requirements are an essential part of NewsKit's offering.

**Task**
Research accessibility in relation to mobile platforms

Consider:

- top level guidance 
- checklists 
- links to resources

**Comment by GeriReid** [comment]
Some initial notes: https://nidigitalsolutions.jira.com/l/cp/BxNn1EVc
No longer needed so moving to done.
